### ISSUE TITLE
change P_seq calculation to max rather than sum

### ISSUE THREAD

**Issue by mwest1066** [mwest1066/randexam#15]
Where we do this:

    P_seq[si,ei,qi] += P[Qi,Vi,Ai]*SCORE_PER_ANSWERS[sum(b[si,qi,:])]

We should max rather than sum. For scantrons with one answer per question, or for which only one answer has a non-zero points value, max and sum are identical. However, if students provide more than one answer to a question, and that question is set to give all answers some points (e.g., if the question is bad), then the above calculation with sum will give too many points.

**Comment by DallasTrinkle** [comment]
Are you sure about the math there? I've been using it the original way, even in cases where I had a bad question (so that I gave points for multiple answers), and it shouldn't give you more than maximum as long as SCORE_PER_ANSWERS[n] <= 1/n for all n>0.

But maybe I'm misunderstanding the change you're proposing? If I have a question where both A and B are "right", and so have a value of 1 point, then I want the point value of a question to be:

sum(b_i * P[a_i]) * SCORE_PER_ANSWER[sum(b)]

because a student should get 1 point for answering A, AB, or B. And if they answer AC or BC, it should be (e.g.), 1/2. If they answer ABC, it should be 2/3, since they've only given 1/3 of an incorrect answer.

At least, that's how I thought about it... what change are you proposing exactly? --d

-- 
Dallas R. Trinkle
Associate Professor
308 Materials Science and Engineering
University of Illinois, Urbana-Champaign
Phone: 217.244.6519
Fax: 217.333.2736
Email: dtrinkle@illinois.edu
Web:	http://dtrinkle.matse.illinois.edu

**Comment by mwest1066** [comment]
Wow, I am very glad that you are following this, and that I submitted a bug report to myself rather than just randomly changing the code. You are of course completely correct. Bug resolved :-)

Matt.




On Feb 26, 2015, at 14:22, Dallas Trinkle <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you sure about the math there? I've been using it the original way, even in cases where I had a bad question (so that I gave points for multiple answers), and it shouldn't give you more than maximum as long as SCORE_PER_ANSWERS[n] <= 1/n for all n>0.

But maybe I'm misunderstanding the change you're proposing? If I have a question where both A and B are "right", and so have a value of 1 point, then I want the point value of a question to be:

sum(b_i * P[a_i]) * SCORE_PER_ANSWER[sum(b)]

because a student should get 1 point for answering A, AB, or B. And if they answer AC or BC, it should be (e.g.), 1/2. If they answer ABC, it should be 2/3, since they've only given 1/3 of an incorrect answer.

At least, that's how I thought about it... what change are you proposing exactly? --d

--
Dallas R. Trinkle
Associate Professor
308 Materials Science and Engineering
University of Illinois, Urbana-Champaign
Phone: 217.244.6519
Fax: 217.333.2736
Email: dtrinkle@illinois.edu<mailto:dtrinkle@illinois.edu>
Web: http://dtrinkle.matse.illinois.edu
